services:
  db:
    image: mysql
    restart: always
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  backend:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
